// <auto-generated />
namespace RepositoryProduct.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TestDev4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestDev4));
        
        string IMigrationMetadata.Id
        {
            get { return "201902250139114_TestDev4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
